name: "Ruff"

permissions:
  contents: read

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
  workflow_dispatch:

jobs:
  gh-ruff:
    if: ${{ !github.event.act }} # skip during local actions testing
    name: Ruff on Python 3.12 and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv pyowm rich
        sudo snap install ruff
    - name: Analyzing the code with Ruff
      run: |
        ruff check $(git ls-files '*.py')
  local-ruff:
    if: ${{ github.event.act }} # run during local actions testing
    name: Ruff on Python 3.xx and windows-latest
    runs-on: windows-latest
    steps:
    - name: Analysing the code with Ruff
      run: |
        ruff check $(git ls-files '*.py')
